name: CI

permissions: {}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Prefer Google mirror globally
        run: |
          echo '{"registry-mirrors":["https://mirror.gcr.io"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Setup Compact Compiler
        uses: midnightntwrk/setup-compact-action@836895c8fffbbea6bd986af2b17e8941ff29d1f8
        with:
          compact-version: '0.31.1'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Compile and test contract
        working-directory: contract
        run: |
          npm run lint
          npm run compact
          npm run typecheck
          npm run build
          npm run test

      - name: Compile shade-cli
        working-directory: shade-cli
        run: |
          npm run lint
          npm run typecheck
          npm run build
